<H1 > Welcome to Data Science Fundamentals: Pandas to Predictions</H1>

<p align="center">
  <img src="Datafain logo.jpg"/>
</p>

Hello. My name is [Ridwan Salahuddeen](https://www.linkedin.com/in/ridwan-salahuddeen/) and I shall be taking you through on this class.

Follow [DataFain](https://www.linkedin.com/company/data-for-all-initiative) on LinkedIn

## Table of Contents
<font >
<ol>
<li> Ice Breaker: What is Data Science?, Data Science Tools, Numpy Introduction, Quiz 1
<li> Importance of Numpy,More Hands-on Use of Numpy,Quiz 2,Assignment 1
<li> Introduction to Pandas: Creating Dataframes and Reading From Files,Quiz 3
<li> More on Pandas: Manipulating Dataframes,Quiz 4,Assignment 2
<li> Introduction to Matplotlib: Plotting Simple Charts,Quiz 5
    
<li> More on Matplotlib: Drawing Inference from plots,Quiz 6,Assignment 3
<li> Types of Machine Learning Algorithms,Quiz 7
<li> Understanding Learning Algorithms - Logistic Regression,Quiz 8,Assignment 4
<li> Using Sci-Kit Learn: Logistic Regression,Sample Classification Problem1,Quiz 9
<li> Sample Classification Problem 2,Quiz 10,Assignment 5
</ol>
</font>

# Ice Breaker: What is Data Science? Data Science Tools - Numpy Introduction - Quiz 1

# Content

### A bit of history
<img src  ='quote.png'>

<!-- Over the past years, the term Data Science -->
Before the turn of the millenium, the term Data was only sparingly used. However, since the turn of the millenium, there has been a rise in the practice and use of the term.

#### Timelines

* **1996**

>For example, one of the earliest mention of the term Data Science in the context it is used today happened in 1996 in a conference meeting by the members of the International Federation of Classification Societies (IFCS), with a mention of Data Science found in the title (“Data science, classification, and related methods”)

* **2002** 

> Launch of Data Science Journal, publishing papers on “the management of data and databases in Science and Technology

* **2009**

> Hal Varian, Google’s Chief Economist, tells the McKinsey Quarterly: “I keep saying the sexy job in the next ten years will be statisticians. People think I’m joking, but who would’ve guessed that computer engineers would’ve been the sexy job of the 1990s? The ability to take data—to be able to understand it, to process it, to extract value from it, to visualize it, to communicate it—that’s going to be a hugely important skill in the next decades… Because now we really do have essentially free and ubiquitous data. So the complimentary scarce factor is the ability to understand that data and extract value from it… I do think those skills—of being able to access, understand, and communicate the insights you get from data analysis—are going to be extremely important. Managers need to be able to access and understand the data themselves.”

[Source: Forbes](https://www.forbes.com/sites/gilpress/2013/05/28/a-very-short-history-of-data-science/#89bed3155cfc)

### A definition of Data Science

> * Data science is an inter-disciplinary field that uses scientific methods, processes, algorithms and systems to extract knowledge and insights from many structural and unstructured data.
> * Data science is a "concept to unify statistics, data analysis, machine learning, domain knowledge and their related methods" in order to "understand and analyze actual phenomena" with data.

[Wikipedia](https://en.wikipedia.org/wiki/Data_science)


### Associated Fields of DS
The following fields all relatate to Data Science and practitioners of Data Science can find themselves doing any of it.
***
>* Statistics
>* Machine Learning
>* Predictive Modelling
>* Data Analysis
>* Data Visualization
>* Data Mining
>* Clustering and Cluster Analysis
>* Artificial intelligence
>* Mathematical Modelling
>* Big data Analytics
>* Deep Learning
>* Reinforcement Learning
>* Data Engineering
>* Business Intelligence, etc.
***

Anybody who practices any of the above field can arguable be called a Data Scientist (which is a much more generalist term).

### Data Scientist Stack
***
**What Skills Do You Need to Be a Data Scientist?**

A data scientist is said to be a person who knows just enough **programming (Python, C++, Java, etc), statistics (or mathematics) and domain knowledge (business knowledge in business field, medical knowledge in medicine, geography knowledge in geographical information systems, etc)** to be able to function in the role.

## NumPy Basics
>* What is Numpy
>* The Basics
>* Creating Arrays
>* Indexing, Slicing and Iterating

***
**PRE-REQUISITES**
***

This program assumes that you have a some foundational knowledge of Python programming language (or any other language)

### What is NumPy?

NumPy stands for 'Numerical Python'. It is a Python Library that supports large, multi-dimensional **arrays and matrices**. It also offers a large collection of **high-level mathematical functions** that operate on these arrays.

### Installing NumPy

Open command prompt (by searching for 'command prompt' from windows menu) and type `pip install numpy`. Press enter (return).

### The Basics

**Array**

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.

**Creating an Array**


An array can be created from a list and its values accessed by indexing, i.e., `array[2]` will access the third index item in array object `array`.

`numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)`

In [3]:
import numpy as np

In [7]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly crea

In [8]:
# Example 1: 1-D arrray

a = np.array([3.0, 1.0, 4.0, 0.0])
print(type(a))
print(a)
print(a.shape)
print(a.dtype)
print(a.size)

<class 'numpy.ndarray'>
[3. 1. 4. 0.]
(4,)
float64
4


In [11]:
# Example 2: 2-D array

a = np.array([[2, 5, 9], [3, 1, 6]])

print(type(a))
print(a)
print(a.shape)
print(a.dtype)

<class 'numpy.ndarray'>
[[2 5 9]
 [3 1 6]]
(2, 3)
int32


In [12]:
# Example 3: Specifying dtype parameter

a = np.array([3, 5, 6], dtype = complex)
print(a)

[3.+0.j 5.+0.j 6.+0.j]


**Array indexing**

`array[4]` will return the forth index item in `array` object

In [13]:
arr = np.array([[7,4,6, 2], [2,3,4, 9], [5,1,0,3]])

print(arr.shape, end = '\n\n')

print(arr, end = '\n\n')

print(arr[0], arr[1], arr[2], end = '\n\n')

print(arr[0,2], end = '\n\n')

print(arr[0,2] == arr[0][2], end = '\n\n')

(3, 4)

[[7 4 6 2]
 [2 3 4 9]
 [5 1 0 3]]

[7 4 6 2] [2 3 4 9] [5 1 0 3]

6

True



**Creating arrays from functions**

NumPy provides some functions for creating arrays without passing the array objects like we have done so far. Let us examine some of them

In [17]:
# Example 1: numpy.arange([start,] stop[, step,], dtype=None)

arr = np.arange(0, 100)
print(arr)

arr = np.arange(5, 15, 2)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 5  7  9 11 13]


In [ ]:
help(np.zeros)

In [18]:
# Example 2: numpy.zeros(shape, dtype=float, order='C')

arr = np.zeros((3,4))
print(arr, end = '\n\n\n')
arr = np.zeros((3,2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [19]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**Additional Resources**

* [Tutorials Point](https://www.tutorialspoint.com/numpy/)
* [Numpy](https://numpy.org/devdocs/user/quickstart.html)